server {
    listen 80;
    server_name app.sagp-qp.com;

    root /var/www/sgq-app-landing;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
}
